title: Jerome Lim # your name (or website title) here
#logo: "/images/?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Technical Artist who enjoys learning new things and applying myself to the challenges required. I strive to consistently produce quality assets on schedule and within technical constraints, have good rapport with my team members and grow confidently as an artist. 
  <br><br>
  I've spent the last 10 years in the industry in Tech Art and Art roles at Virtually Live Singapore, Bandai Namco Singapore and LucasArts Singapore.
  <br><br>
  <a href="https://www.linkedin.com/in/jerome-lim-36005810/">View My LinkedIn Profile</a> 
  <br><br>
  View My CV <a href="/docs/JeromeLim_CV_2019.pdf">[PDF]</a> <a href="/docs/JeromeLim_CV_2019.docx">[DOCX]</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
